model_name: "p-prodec2-reinforce-cnf-pytorch"
model_type: "reinforce"
version: "2.0"
has_meta_data: false #true
#train_path: ["../../datasets/SAT/p-cnf-3-10-large.json"]
#validation_path: ["../../datasets/SAT/cnf-10.json"]
#test_path: ["../../datasets/SAT/3SAT-100"] # ["../../datasets/SAT/3SAT-100"] # ["../../datasets/SAT/4SAT-100"] # ["../../datasets/SAT/cnf-10.json"] #
#model_path: "../../Trained-models/SAT"
train_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/train_0.json","/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/train_1.json","/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/train_2.json"]
validation_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/test.json"]
test_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/validate.json"]
model_path: "Trained-models/SAT8"
repetition_num: 1
train_epoch_size: 200000
epoch_num: 500
label_dim: 1
edge_feature_dim: 1
meta_feature_dim: 0 #1
error_dim: 3
metric_index: 0
prediction_dim: 1
hidden_dim: 157  # 110
mem_hidden_dim: 50
agg_hidden_dim: 50  # 135
mem_agg_hidden_dim: 50  # 50
classifier_dim: 50 # 30  # 100
batch_size: 5000
learning_rate: 0.0001
exploration: 0.1
verbose: true
randomized: true
train_inner_recurrence_num: 1
train_outer_recurrence_num: 20
test_recurrence_num: 1000
max_cache_size: 100000
dropout: 0.2
clip_norm: 0.65
weight_decay: 0.0000000001
loss_sharpness: 5
train_batch_limit: 5100000
test_batch_limit: 40000000
min_n: 10
max_n: 100
min_alpha: 2
max_alpha: 10
min_k: 2
max_k: 10
local_search_iteration: 1000
epsilon: 0.5
pi: 0.01
decimation_probability: 0.5
lambda: 1
