model_name: "p-prodec2-gcnf-10-100-pytorch"
model_type: "np-nd-np"
version: "8.0g-origin"
has_meta_data: false # true
#train_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/uniform1/uniform_3.json", "/home/ziwei/Workspace/PDP-Solver/datasets/uniform1/uniform_2.json","datasets/uniform1/uniform_4.json", "datasets/uniform2/uniform_3.json", "/home/ziwei/Workspace/PDP-Solver/datasets/uniform2/uniform_2.json","/home/ziwei/Workspace/PDP-Solver/datasets/uniform2/uniform_4.json"]
train_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/uniform1/competition.json"]
validation_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/uniform1/competition.json", "datasets/uniform1/uniform_0.json"]
test_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/uniform1/uniform_1.json",  "/home/ziwei/Workspace/PDP-Solver/datasets/uniform1/uniform_1.json"] #["../../datasets/SAT/M-4SAT-validation-2/M-4SAT-validation-2_0_7.0_10.0.json"] #["../../datasets/SAT/4SAT-subsample"] #["../../datasets/SAT/M0-4SAT-100"] # ["../../datasets/SAT/3SAT-100"] # ["../../datasets/SAT/4SAT-100"] # ["../../datasets/SAT/cnf-10.json"] #
model_path: "/home/ziwei/Workspace/PDP-Solver/Trained-models/SAT"
repetition_num: 1
train_epoch_size: 40000
epoch_num: 500
label_dim: 1
edge_feature_dim: 1
meta_feature_dim: 0 # 1
error_dim: 3
metric_index: 0
prediction_dim: 1
hidden_dim: 100  # 110
mem_hidden_dim: 136 #100
agg_hidden_dim: 100  # 135
mem_agg_hidden_dim: 50  # 50
classifier_dim: 50  # 100
batch_size: 3000
learning_rate: 0.0001
exploration: 0.1
verbose: true
randomized: true
train_inner_recurrence_num: 1
train_outer_recurrence_num: 10
test_recurrence_num: 2000 #8800
max_cache_size: 100000
dropout: 0.2
clip_norm: 0.65
weight_decay: 0.0000000001
loss_sharpness: 5
train_batch_limit: 4000000
test_batch_limit: 4000000
generator: "uniform"
min_n: 4
max_n: 100
min_alpha: 2
max_alpha: 10
min_k: 2
max_k: 10
local_search_iteration: 3000
epsilon: 0.5 #0.5
lambda: 1
# python build/scripts-3.6/satyr-train-test.py config/Train/p-prodec2-gcnf-10-100-pytorch.yaml