model_name: "p-prodec2-modular-variable-pytorch-2"
model_type: "np-nd-np"
version: "1.0g"
has_meta_data: false # true
train_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/train_0.json","/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/train_1.json","/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/train_2.json"]
validation_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/test.json"]
test_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT8/validate.json"]
model_path: "Trained-models/SAT8"
repetition_num: 1
train_epoch_size: 40000
epoch_num: 500
label_dim: 1
edge_feature_dim: 1
meta_feature_dim: 0 # 1
error_dim: 3
metric_index: 0
prediction_dim: 1
hidden_dim: 150  # 110
mem_hidden_dim: 135
agg_hidden_dim: 135  # 135
mem_agg_hidden_dim: 100  # 50
classifier_dim: 50  # 100
batch_size: 5000
learning_rate: 0.0001
exploration: 0.1
verbose: true
randomized: true
train_inner_recurrence_num: 1
train_outer_recurrence_num: 10
test_recurrence_num: 200
max_cache_size: 100000
dropout: 0.3
clip_norm: 0.65
weight_decay: 0.0000000001
loss_sharpness: 5
train_batch_limit: 6500000
test_batch_limit: 40000000
# generator: "v-modular"
# min_n: 5
# max_n: 100
# min_alpha: 5
# max_alpha: 10
# min_k: 2
# max_k: 10
# min_q: 0.8
# max_q: 0.9
# min_c: 10
# max_c: 20
local_search_iteration: 0
epsilon: 0.5
lambda: 0.95
