model_name: "p-prodec2-modular-variable-pytorch"
model_type: "np-nd-np"
version: "3.0g"
#train_path: ["../../datasets/SAT/p-cnf-3-10-large.json"]
#validation_path: ["../../datasets/SAT/M-4SAT-validation-2/M-4SAT-validation-2_0_7.0_10.0.json"]
#test_path: ["../../datasets/SAT/M-4SAT-validation-2/M-4SAT-validation-2_0_7.0_10.0.json"] #["../../datasets/SAT/M0-4SAT-100"] #["../../datasets/SAT/cnf-10.json"] #["../../datasets/SAT/sat-race-test.json"] # ["../../datasets/SAT/cnf-10.json"] #["../../datasets/SAT/3SAT-100"] #
#model_path: "../../Trained-models/SAT"
# train_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT/v-modular_0.json","/home/ziwei/Workspace/PDP-Solver/datasets/SAT/v-modular_2.json","/home/ziwei/Workspace/PDP-Solver/datasets/SAT/v-modular_4.json"]
# validation_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT/v-modular_1.json"]
# test_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/SAT/v-modular_3.json"]  #[],["datasets/SAT2/v-modular_4.json"] #["../../datasets/SAT/4SAT-test"] #  ["../../datasets/SAT/cnf-10.json"] #
train_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/g2sat/train.json"]
validation_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/g2sat/validate.json"]
test_path: ["/home/ziwei/Workspace/PDP-Solver/datasets/g2sat/test.json"]
#train_path: ['datasets/test_2']
#test_path: ['datasets/test_2']
#validation_path: ['datasets/test_2']
model_path: "Trained-models/g2sat"
repetition_num: 1
train_epoch_size: 40000
epoch_num: 500
label_dim: 1
edge_feature_dim: 1
meta_feature_dim: 0 # 1
error_dim: 3
metric_index: 0
prediction_dim: 1
hidden_dim: 128  # 110
mem_hidden_dim: 150 #100 150
agg_hidden_dim: 96  # 135 100
mem_agg_hidden_dim: 48  # 50  cuda memory
classifier_dim: 100  # 100 50
batch_size: 5000
# learning_rate: 0.0001
learning_rate: 0.001
exploration: 0.1
verbose: true
randomized: true
train_inner_recurrence_num: 1
train_outer_recurrence_num: 10
test_recurrence_num: 200
max_cache_size: 100000
dropout: 0.2  #0.2
clip_norm: 0.65
#clip_norm: 0.7
#weight_decay: 0.0000000001
weight_decay: 0.000000001
loss_sharpness: 5
train_batch_limit: 5800000
# train_batch_limit: 20000000
test_batch_limit: 5800000
#--------------IF USE GENERATOR--------------
#generator: "v-modular"
#min_n: 5
#max_n: 100
#min_alpha: 5
#max_alpha: 10
#min_k: 2
#max_k: 10
#min_q: 0.8
#max_q: 0.9
#min_c: 10
#max_c: 20
#----------------------------
local_search_iteration: 0
epsilon: 0.5
lambda: 1
batch_replication: 3
# python build/scripts-3.6/satyr-train-test.py config/Train/p-prodec2-modular-variable-pytorch.yaml 