model_name: "pdp-model-1.0"
model_type: "np-nd-np"
version: "2.0g"
has_meta_data: false # true
train_path: ["/Users/zhangziwei/workspace/python/PDP-Solver/datasets/SAT/uniform_0.json"]
validation_path: ["/Users/zhangziwei/workspace/python/PDP-Solver/datasets/SAT/uniform_1.json"]
test_path: ["/Users/zhangziwei/workspace/python/PDP-Solver/datasets/SAT/uniform_2.json"] #["../../datasets/SAT/M-4SAT-validation-2/M-4SAT-validation-2_0_7.0_10.0.json"] #["../../datasets/SAT/4SAT-subsample"] #["../../datasets/SAT/M0-4SAT-100"] # ["../../datasets/SAT/3SAT-100"] # ["../../datasets/SAT/4SAT-100"] # ["../../datasets/SAT/cnf-10.json"] #
model_path: "Trained-models/"
repetition_num: 1
train_epoch_size: 10
epoch_num: 1
label_dim: 1
edge_feature_dim: 1
meta_feature_dim: 0 # 1
error_dim: 3
metric_index: 0
prediction_dim: 1
#hidden_dim: 150  # 110
hidden_dim: 110  # 110
#mem_hidden_dim: 100
#agg_hidden_dim: 100  # 135
mem_hidden_dim: 50
agg_hidden_dim: 50  # 135
mem_agg_hidden_dim: 50  # 50
classifier_dim: 50  # 100
batch_size: 1
#learning_rate: 0.0001
learning_rate: 0.001
exploration: 0.1
verbose: true
randomized: true
train_inner_recurrence_num: 1
train_outer_recurrence_num: 10
test_recurrence_num: 110
max_cache_size: 10000
dropout: 0.2
clip_norm: 0.65
weight_decay: 0.0000000001
loss_sharpness: 5
train_batch_limit: 40000
test_batch_limit: 400000
generator: "uniform"
min_n: 100
max_n: 150
min_alpha: 2
max_alpha: 10
min_k: 3
max_k: 5
local_search_iteration: 10
epsilon: 0.5
lambda: 1
