import numpy as np
import pandas as pd

dataset1 = pd.read_table('datasets/uniform1/uniform_0.json')
dataset2 = pd.read_table('datasets/uniform1/uniform_1.json')
dataset3 = pd.read_table('datasets/uniform1/uniform_2.json')
dataset4 = pd.read_table('datasets/uniform1/uniform_3.json')
dataset5 = pd.read_table('datasets/uniform1/uniform_4.json')
# print(dataset1.size, dataset2.size, dataset3.size, dataset4.size, dataset5.size)
array1 = np.array(dataset1)
array2 = np.array(dataset2)
array3 = np.array(dataset3)
array4 = np.array(dataset4)
array5 = np.array(dataset5)
all_set = np.concatenate((array1, array2, array3, array4, array5), axis = 0)
print(all_set.shape)
np.random.shuffle(all_set)
dataframe = pd.DataFrame(all_set)
train_rows = int(dataframe.size * 0.2)
test_rows = int(dataframe.size * 0.2)

train1 = pd.DataFrame(all_set[:train_rows])
train2 = pd.DataFrame(all_set[train_rows:train_rows*2])
train3 = pd.DataFrame(all_set[train_rows*2:train_rows*3])
test = pd.DataFrame(all_set[train_rows*3:(train_rows*3 + test_rows)])
validate = pd.DataFrame(all_set[(train_rows*3 + test_rows):])
print(train1.size, train2.size, train3.size, test.size, validate.size)
train1.to_csv('datasets/uniform1/train0.json', index = False, header = False)
train2.to_csv('datasets/uniform1/train1.json', index = False, header = False)
train3.to_csv('datasets/uniform1/train2.json', index = False, header = False)
test.to_csv('datasets/uniform1/test.json', index = False, header = False)
validate.to_csv('datasets/uniform1/validate.json', index = False, header = False)
